name: NodeJS Github Action

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3 # checkout the repo and download it to run on server

      - name: Use Node
        uses: actions/setup-node@v4 # install nodejs(18) with tools like npm and yarn needed for workflows
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        
      - name: Run test
        run: npm test

      - run: npm install
      - run: npm test

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Link Railway Project
        run: railway link --project bd004e0f-f45d-4360-b00b-44ccbb2c001f
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}