name: NodeJS Github Action

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3 # checkout the repo and download it to run on server

      - name: Use Node
        uses: actions/setup-node@v4 # install nodejs(18) with tools like npm and yarn needed for workflows
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        
      - name: Run test
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: e11bacde-09a5-41b1-8baf-be547c40408e
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: railway up --service=${{ env.SVC_ID }}